version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      # MYSQL_USER: electronote
      # MYSQL_PASSWORD: password
    cap_add:
      - SYS_NICE
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    working_dir: /electronote
    command: bundle exec unicorn -p 3000 -c /electronote/config/unicorn.rb
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      # - tmp_data:/electronote/tmp
      - .:/electronote
      - /var/tmp
      - bundle_path:/usr/local/bundle
    # environment:
      # - BUNDLE_PATH=/electronote/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile:  ./docker/nginx/Dockerfile
    volumes:
      - nginx_log-data:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes_from:
      - app
volumes:
  nginx_log-data:
  bundle_path:
  # tmp_data:
